# Generated by Django 6.1.1 on 2026-09-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hire_date', models.DateField()),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
